#!/usr/bin/env python3
# ci-line: E | Simultaneous Solver (staged elimination: every solution and bank rule recomputed; SR-13 step marking and a Stage 4 problem on the phone keypad in Chromium; Stage 5 word problems: unique solutions, every key form marked, tiles build every key, a session played) |
"""Simultaneous Solver: every bank rule and every answer, recomputed; the staged method played in Chromium.

Foundation (Stages 1-4, generated by scripts/gen-simultaneous.py, read from the page between the GENERATED
BANK markers). For every problem:
  - the pair has exactly one solution (exact fractions), it is whole, from -10 to 10, and it is the stored one;
  - every coefficient is 1 to 12 in size;
  - the stored neatest multipliers are the LCM pair for the letter, and at most 5 (Stage 4: both letters,
    and the stored neater letter follows the rule: the smaller LCM, then fewer equations scaled);
and for every stage: at least 45 problems, none repeated (in either order); Stage 1 has some x1 cases;
in Stages 2-4 at least two-thirds have a negative coefficient or constant, and each kind of negative work
(subtracting a negative, adding two negatives, a negative result; on the neatest scaling, (1) first) is at
least an eighth of the stage. The page's bank must also be exactly what the generator makes.

A-Level (four options, read between the ALEVEL BANK markers): every system solved with SymPy, the key
recomputed from what the question asks, and no two options equal in value (SR-4).

The page in Chromium (stub server), unless --static:
  - Stage 1 marking: for every Stage 1 problem, all 144 multiplier pairs 1..12 are marked, and exactly the
    valid ones (|m1 a| = |m2 b|) score; negatives are valid, x0 is blocked, 1.5 is not marked;
  - the page's scaling, add/subtract rule and combined equation agree with this script on every problem;
  - at 390px: x4/x6 where x2/x3 is neatest scores and shows x2/x3; choosing add where subtract was needed
    shows the letter doubling; a wrong combined equation shows the working term by term (4 - (-5) = 9);
  - a full game of every stage, all right: full marks, one leaderboard entry on the stage's own board, every
    analytics event carrying mode, no timer; the A-Level level likewise on its kept 'alevel' board;
  - a full Stage 4 problem played on MaffsKeypad at 390x844 (and 375x667, 320x568, each also in Aa mode):
    every step and its keypad in the window together, never the system keyboard.

Self-test (run first, every time): a non-integer solution, a wrong neatest pair, a positives-only stage and
a wrong A-Level key are planted in copies of the banks; each must fail.

Stage 5 (SIM-S5, Jon, 9 Oct 2026; read between the WORDS BANK markers): the 40 word problems are worded as the
contract gives them (docs/handover/contracts/ or docs/history/contracts/2026-10-09-sim-s5.md); each pair of keys
has exactly the one solution held here (S5_SOLUTIONS; never in the page), and it is positive; the Let line names
both letters; every source quote is in its problem; every distractor tile is a spare number in the text or a
pounds amount in pence. In Chromium, the page's own marker (EqTiles): for every key, the key, its sides swapped,
a rearranged form and a scaled form are right; a partly scaled form, an arithmetic slip and the same key twice
are wrong; the page's tiles build every key; 60 sessions each draw eight problems, none repeated, three W and
three E at least; a session built by tapping tiles at 390x844 and 1280x900 (right, swapped, one wrong): marks,
one event a problem, the feedback quoting the words, one submit on foundation-s5, no sideways scroll; MaffsLock
with its real window: a triple click on Check marks once and a tile does nothing after it. Its self-test plants
a problem with two solutions, a marker that compares equations as written, and tiles that cannot build a key.

    python scripts/verify-simultaneous-solver.py            # self-test, banks, then the page in Chromium
    python scripts/verify-simultaneous-solver.py --static   # self-test and banks only
"""
import argparse
import copy
import importlib.util
import json
import math
import os
import re
import sys
from decimal import Decimal, getcontext
from fractions import Fraction

import sympy as sp

getcontext().prec = 40

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "games", "simultaneous-solver", "index.html")
SLUG = "simultaneous-solver"
STAGES = ["stage1", "stage2", "stage3", "stage4"]
BOARDS = {"stage1": "foundation-s1", "stage2": "foundation-s2", "stage3": "foundation-s3", "stage4": "foundation-s4"}
ROUNDS = {"stage1": 10, "stage2": 8, "stage3": 6, "stage4": 6}
STEPS = {"stage1": 1, "stage2": 3, "stage3": 5, "stage4": 5}
MIN_PER_STAGE, MIN_ALEVEL = 45, 40


def load_gen():
    spec = importlib.util.spec_from_file_location("gen_simultaneous", os.path.join(ROOT, "scripts", "gen-simultaneous.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def block(src, start, end):
    m = re.search(re.escape(start) + r"\s*var\s+\w+\s*=\s*(.*?);?\s*" + re.escape(end), src, re.S)
    if not m:
        raise SystemExit("verify-simultaneous-solver: no %s ... %s block in the page" % (start, end))
    return json.loads(m.group(1))


def read_banks(path=PAGE):
    src = open(path, encoding="utf-8").read()
    return (block(src, "/* GENERATED BANK START */", "/* GENERATED BANK END */"),
            block(src, "/* ALEVEL BANK START */", "/* ALEVEL BANK END */"))


# ---------------------------------------------------------------- Foundation rules
def lcm_pair(p, q):
    l = abs(p) * abs(q) // math.gcd(abs(p), abs(q))
    return [l // abs(p), l // abs(q)]


def exact_solution(e):
    (a1, b1, c1), (a2, b2, c2) = e
    det = a1 * b2 - a2 * b1
    if det == 0:
        return None
    return Fraction(c1 * b2 - c2 * b1, det), Fraction(a1 * c2 - a2 * c1, det)


def neater_letter(e):
    def cost(i):
        m = lcm_pair(e[0][i], e[1][i])
        return (abs(e[0][i]) * m[0], sum(v != 1 for v in m))
    cx, cy = cost(0), cost(1)
    return "x" if cx < cy else "y" if cy < cx else "either"


def negative_work(e, letter):
    """The kinds of negative work in eliminating this letter, neatest scaling, (1) first."""
    i = 0 if letter == "x" else 1
    m = lcm_pair(e[0][i], e[1][i])
    s = [[m[0] * v for v in e[0]], [m[1] * v for v in e[1]]]
    sub = (s[0][i] > 0) == (s[1][i] > 0)
    comb = [s[0][k] - s[1][k] if sub else s[0][k] + s[1][k] for k in range(3)]
    kinds = set()
    if sub and any(v < 0 for v in s[1]):
        kinds.add("subtracting a negative")
    if not sub and any(u < 0 and v < 0 for u, v in zip(s[0], s[1])):
        kinds.add("adding two negatives")
    if comb[1 - i] < 0 or comb[2] < 0:
        kinds.add("a negative result")
    return kinds


def check_foundation(bank, report=None):
    fails = []
    for st in STAGES:
        items = bank.get(st, [])
        if len(items) < MIN_PER_STAGE:
            fails.append("%s: %d problems, at least %d needed" % (st, len(items), MIN_PER_STAGE))
        seen, ids = {}, set()
        for it in items:
            iid, e = it.get("id"), it.get("e")
            if iid in ids:
                fails.append("%s: id %s used twice" % (st, iid))
            ids.add(iid)
            if not (isinstance(e, list) and len(e) == 2 and all(isinstance(r, list) and len(r) == 3 and all(isinstance(v, int) for v in r) for r in e)):
                fails.append("%s: malformed equations %r" % (iid, e))
                continue
            if any(not 1 <= abs(v) <= 12 for r in e for v in r[:2]):
                fails.append("%s: a coefficient is not 1 to 12 in size: %r" % (iid, e))
            sol = exact_solution(e)
            if sol is None:
                fails.append("%s: no single solution (no solution, or infinitely many): %r" % (iid, e))
                continue
            x, y = sol
            if x.denominator != 1 or y.denominator != 1:
                fails.append("%s: the solution is not whole: x = %s, y = %s" % (iid, x, y))
            elif not (-10 <= x <= 10 and -10 <= y <= 10):
                fails.append("%s: the solution x = %s, y = %s is outside -10..10" % (iid, x, y))
            elif (int(x), int(y)) != (it.get("x"), it.get("y")):
                fails.append("%s: stored x = %r, y = %r, but the solution is x = %s, y = %s" % (iid, it.get("x"), it.get("y"), x, y))
            k = tuple(sorted(tuple(r) for r in e))
            if k in seen:
                fails.append("%s: the same problem as %s" % (iid, seen[k]))
            seen[k] = iid
            letters = ["x", "y"] if st == "stage4" else [it.get("elim")]
            for L in letters:
                if L not in ("x", "y"):
                    fails.append("%s: elim is %r, not x or y" % (iid, L))
                    continue
                i = 0 if L == "x" else 1
                want = lcm_pair(e[0][i], e[1][i])
                got = it.get("m" + L) if st == "stage4" else it.get("m")
                if got != want:
                    fails.append("%s: the neatest multipliers for %s are %r, the bank says %r" % (iid, L, want, got))
                if max(want) > 5:
                    fails.append("%s: the neatest multipliers for %s are %r, more than 5" % (iid, L, want))
            if st == "stage4" and it.get("neat") != neater_letter(e):
                fails.append("%s: the neater letter is %s, the bank says %r" % (iid, neater_letter(e), it.get("neat")))
        if st == "stage1":
            ones = sum(1 for it in items if 1 in (it.get("m") or []))
            if ones < 5:
                fails.append("stage1: only %d problems with a x1 multiplier (some are needed)" % ones)
            if report is not None:
                report.append("stage1: %d problems, %d with a x1 multiplier" % (len(items), ones))
        else:
            neg, kinds = 0, {"subtracting a negative": 0, "adding two negatives": 0, "a negative result": 0}
            for it in items:
                if any(v < 0 for r in it["e"] for v in r):
                    neg += 1
                L = it.get("elim") or (it.get("neat") if it.get("neat") in ("x", "y") else "x")
                for kd in negative_work(it["e"], L):
                    kinds[kd] += 1
            n = max(len(items), 1)
            if 3 * neg < 2 * n:
                fails.append("%s: only %d of %d problems have a negative coefficient or constant (two-thirds needed)" % (st, neg, n))
            for kd, c in kinds.items():
                if 8 * c < n:
                    fails.append("%s: only %d of %d problems involve %s (an eighth needed)" % (st, c, n, kd))
            if report is not None:
                report.append("%s: %d problems; a negative coefficient or constant in %d (%.0f%%); %s"
                              % (st, n, neg, 100.0 * neg / n, ", ".join("%s %d" % kv for kv in kinds.items())))
    return fails


# ---------------------------------------------------------------- A-Level keys
X, Y = sp.symbols("x y")


def tex_expr(t):
    s = t.replace("\\dfrac", "\\tfrac")
    s = re.sub(r"\\sqrt\{([^{}]*)\}", r"sqrt(\1)", s)
    s = re.sub(r"\\tfrac\{([^{}]*)\}\{([^{}]*)\}", r"((\1)/(\2))", s)
    s = s.replace("^", "**")
    s = re.sub(r"(\d)\s*([xy(]|sqrt)", r"\1*\2", s)
    if "\\" in s:
        raise ValueError("unparsed TeX in %r" % t)
    return sp.nsimplify(sp.sympify(s, locals={"x": X, "y": Y}))


def alevel_key(item):
    eqs = []
    for t in item["sys"]:
        l, r = t.split("=")
        eqs.append(sp.Eq(tex_expr(l), tex_expr(r)))
    sols = [s for s in sp.solve(eqs, [X, Y], dict=True) if all(v.is_real for v in s.values())]
    sols = list({(sp.simplify(s[X]), sp.simplify(s[Y])) for s in sols})
    ask = item["ask"]
    xs = sorted({s[0] for s in sols}, key=lambda v: float(v))
    if ask == "How many solutions?":
        return sp.Integer(len(sols))
    if ask in ("Find x", "Find y"):
        if len(sols) != 1:
            raise ValueError("%d solutions for a 'Find' question" % len(sols))
        return sols[0][0] if ask == "Find x" else sols[0][1]
    if ask == "Find the values of x (sum)":
        return sp.simplify(sum(xs))
    m = re.match(r"Find the (positive|negative|non-zero|larger|smaller) ([xy]) value$", ask)
    if not m:
        raise ValueError("an ask this script cannot read: %r" % ask)
    vals = sorted({s[0 if m.group(2) == "x" else 1] for s in sols}, key=lambda v: float(v))
    pick = {"positive": [v for v in vals if v > 0], "negative": [v for v in vals if v < 0],
            "non-zero": [v for v in vals if v != 0], "larger": vals[-1:] if len(vals) == 2 else [],
            "smaller": vals[:1] if len(vals) == 2 else []}[m.group(1)]
    if len(pick) != 1:
        raise ValueError("'%s' picks %d values from %r" % (ask, len(pick), vals))
    return pick[0]


def check_alevel(items):
    fails, ids = [], set()
    if len(items) < MIN_ALEVEL:
        fails.append("alevel: %d questions, at least %d needed" % (len(items), MIN_ALEVEL))
    for it in items:
        iid = it.get("id")
        if iid in ids:
            fails.append("alevel: id %s used twice" % iid)
        ids.add(iid)
        try:
            key = alevel_key(it)
            opts = [it["correct"]] + list(it["distractors"])
            vals = [tex_expr(o) for o in opts]
        except Exception as exc:
            fails.append("%s: %s" % (iid, exc))
            continue
        if len(opts) != 4:
            fails.append("%s: %d options, 4 needed" % (iid, len(opts)))
        if sp.simplify(vals[0] - key) != 0:
            fails.append("%s: the key is %s, but %r (%s) is stored" % (iid, key, it["correct"], vals[0]))
        for a in range(len(vals)):
            for b in range(a + 1, len(vals)):
                if sp.simplify(vals[a] - vals[b]) == 0:
                    fails.append("%s: options %r and %r are equal in value (SR-4)" % (iid, opts[a], opts[b]))
    return fails


# ---------------------------------------------------------------- self-test
def selftest(bank, alevel):
    out = []

    def plant(name, fn, needle, which="f"):
        b, a = copy.deepcopy(bank), copy.deepcopy(alevel)
        fn(b, a)
        f = check_foundation(b) if which == "f" else check_alevel(a)
        hit = [x for x in f if needle in x]
        out.append(None if hit else "self-test: the planted %s was not caught" % name)

    def non_integer(b, a):
        it = b["stage2"][0]
        for d in range(1, 13):          # bounded: the first change of c1 that makes the solution not whole
            e = copy.deepcopy(it["e"])
            e[0][2] += d
            s = exact_solution(e)
            if s and (s[0].denominator != 1 or s[1].denominator != 1):
                it["e"] = e
                return

    def wrong_pair(b, a):
        b["stage1"][0]["m"] = [v * 2 for v in b["stage1"][0]["m"]]

    def positives_only(b, a):
        for it in b["stage3"]:
            x, y = abs(it["x"]), abs(it["y"])
            e = [[abs(r[0]), abs(r[1])] for r in it["e"]]
            it["e"] = [[r[0], r[1], r[0] * x + r[1] * y] for r in e]
            it["x"], it["y"] = x, y

    def wrong_key(b, a):
        a[0]["correct"] = "7"

    plant("non-integer solution", non_integer, "not whole")
    plant("wrong neatest pair", wrong_pair, "the bank says")
    plant("positives-only stage", positives_only, "have a negative coefficient or constant")
    plant("wrong A-Level key", wrong_key, "the key is", which="a")
    return [x for x in out if x]


# ---------------------------------------------------------------- the page in Chromium
PHONES = [(390, 844), (375, 667), (320, 568)]
FIT_JS = """() => { const R = e => e && e.offsetParent !== null ? e.getBoundingClientRect() : null;
  const step = R(document.getElementById('step')), kp = R(document.querySelector('#kpHolder .maffs-keypad-panel')),
    chk = R(document.getElementById('checkRow')), body = R(document.getElementById('stepBody')), ae = document.activeElement;
  const bottom = Math.max(kp ? kp.bottom : 0, chk ? chk.bottom : 0, body ? body.bottom : 0);
  return { top: step ? step.top : -1, bottom: bottom, fold: innerHeight - 40, focused: !!ae && ae.tagName === 'INPUT',
    sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }; }"""


def play(fails, bank, alevel, katex_dir=None, shots=None):
    import asyncio
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import bank_common as bc

    def right_answers(it, stage, letter=None):
        """The answer for each step, in order: (kind, value)."""
        L = letter or it.get("elim")
        i = 0 if L == "x" else 1
        m = lcm_pair(it["e"][0][i], it["e"][1][i])
        s = [[m[0] * v for v in it["e"][0]], [m[1] * v for v in it["e"][1]]]
        sub = (s[0][i] > 0) == (s[1][i] > 0)
        comb = [s[0][k] - s[1][k] if sub else s[0][k] + s[1][k] for k in range(3)]
        o = "y" if L == "x" else "x"
        steps = []
        if stage == "stage4":
            steps.append(("choose", L))
        steps.append(("type", [str(m[0]), str(m[1])]))
        if stage != "stage1":
            steps.append(("choose", "sub" if sub else "add"))
            steps.append(("type", [str(comb[1 - i]), str(comb[2])]))
        if stage in ("stage3", "stage4"):
            steps.append(("type", [str(it[o])]))
            steps.append(("type", [str(it[L])]))
        return steps

    async def run(base):
        from playwright.async_api import async_playwright
        async with async_playwright() as p:
            browser = await p.chromium.launch()

            async def route(r):
                u = r.request.url
                if katex_dir and u.startswith("https://cdn.jsdelivr.net/npm/katex"):
                    f = os.path.join(katex_dir, u.split("/dist/", 1)[1].split("?")[0])
                    await (r.fulfill(path=f) if os.path.exists(f) else r.abort())
                elif u.startswith(base) or u.startswith("https://cdn.jsdelivr.net/npm/katex"):
                    await r.continue_()
                else:
                    await r.abort()

            async def fresh(w, h, touch=False, aa=False):
                ctx = await browser.new_context(viewport={"width": w, "height": h}, has_touch=touch, is_mobile=touch)
                await bc.no_next_floor(ctx)
                await ctx.add_init_script(bc.NO_LOCK_FRESH_INIT)   # MaffsLock's 300 ms window: the driver answers at once (F1 batch 8)
                if aa:
                    await ctx.add_init_script("try { localStorage.setItem('mfg_accessible', 'true'); } catch (e) {}")
                await ctx.route("**/*", route)
                page = await ctx.new_page()
                errors = []
                page.on("pageerror", lambda e: errors.append(str(e)))
                await page.goto(base + "/games/%s/" % SLUG, wait_until="load")
                # Every font face the page declares (KaTeX's come from the CDN), loaded before anything is played:
                # a face arriving after stepInView() has scrolled grows the step by ~25px at 320x568, so the fit
                # verdict depended on network timing (F1 batch 8; main showed it 4 runs in 8).
                await page.evaluate("() => Promise.all([...document.fonts].map(f => f.load().catch(() => 0))).then(() => document.fonts.ready).then(() => 0)")
                await page.wait_for_function("!!window.SS && !!window.SS.ui")
                await page.evaluate("""() => { window.__events = []; window.__submits = [];
                  window.mfg = function (n, p) { window.__events.push([n, p]); };
                  if (window.MaffsLeaderboard) MaffsLeaderboard.submitScore = function (s, l, sc, n) {
                    window.__submits.push([s, l, sc, n]); return Promise.resolve({}); }; }""")
                return ctx, page, errors

            async def do(page, kind, val):
                if kind == "choose":
                    if not await page.evaluate("v => SS.ui.choose(v)", val):
                        fails.append("page: no %r choice at step %r" % (val, await page.evaluate("SS.ui.state()")))
                else:
                    await page.evaluate("v => SS.ui.type(v)", val)
                    await page.click("#checkBtn")

            async def next_btn(page):
                if await page.locator(".maffs-next").count():
                    await page.click(".maffs-next")
                    return True
                return False

            ctx, page, errors = await fresh(390, 844)
            # 1. Stage 1 marking: every pair 1..12, negatives, x0 and 1.5.
            res = await page.evaluate("""(items) => items.map(it => { const out = [];
              for (let a = 1; a <= 12; a++) for (let b = 1; b <= 12; b++) out.push(SS.markMult(it.e, it.elim, String(a), String(b)).result);
              const n = it.m;
              return { grid: out, neg: SS.markMult(it.e, it.elim, String(-n[0]), String(n[1])).result,
                zero: SS.markMult(it.e, it.elim, '0', String(n[1])).result, half: SS.markMult(it.e, it.elim, '1.5', String(n[1])).result,
                neatest: SS.markMult(it.e, it.elim, String(n[0]), String(n[1])).neatest }; })""", bank["stage1"])
            pairs = 0
            for it, r in zip(bank["stage1"], res):
                i = 0 if it["elim"] == "x" else 1
                k = 0
                for a in range(1, 13):
                    for b in range(1, 13):
                        want = "correct" if abs(a * it["e"][0][i]) == abs(b * it["e"][1][i]) else "wrong"
                        if r["grid"][k] != want:
                            fails.append("page, %s: x%d and x%d marked %s, expected %s" % (it["id"], a, b, r["grid"][k], want))
                        k += 1
                        pairs += 1
                if r["neg"] != "correct" or r["zero"] != "blocked" or r["half"] != "whole" or not r["neatest"]:
                    fails.append("page, %s: negative %s, x0 %s, x1.5 %s, neatest flagged %s" % (it["id"], r["neg"], r["zero"], r["half"], r["neatest"]))
            # 2. The page's algebra against this script's on every problem.
            for st in STAGES[1:]:
                for it in bank[st]:
                    L = it.get("elim") or (it["neat"] if it["neat"] in ("x", "y") else "x")
                    steps = right_answers(it, st, L)
                    got = await page.evaluate("""([it, L]) => { const i = L === 'x' ? 0 : 1, m = SS.neat(it.e[0][i], it.e[1][i]),
                      s = SS.scale(it.e, m), op = SS.opFor(s, L), c = SS.combine(s, L, op); return [op, String(c.K), String(c.C)]; }""", [it, L])
                    want = [steps[-4 if st != "stage2" else -2][1], steps[-3 if st != "stage2" else -1][1][0], steps[-3 if st != "stage2" else -1][1][1]]
                    if got != want:
                        fails.append("page, %s: op and combined %r, expected %r" % (it["id"], got, want))
            # 3a. x4/x6 where x2/x3 is neatest (or the first both-scaled pair, doubled).
            it = next((x for x in bank["stage1"] if x["m"] == [2, 3]), None) or next(x for x in bank["stage1"] if min(x["m"]) > 1)
            n = it["m"]
            await page.evaluate("id => SS.ui.startWith('stage1', [id])", it["id"])
            await do(page, "type", [str(2 * n[0]), str(2 * n[1])])
            got = await page.evaluate("""() => { const w = document.querySelector('#working .wl'), ne = w && w.querySelector('.neatest');
              return [SS.ui.score(), w ? w.className : '', ne ? ne.innerText.replace(/\\s+/g, ' ') : null]; }""")
            if got[0] != 1 or "right" not in got[1] or not got[2] or ("×%d" % n[0]) not in got[2] or ("×%d" % n[1]) not in got[2]:
                fails.append("page, %s: x%d/x%d (neatest x%d/x%d) scored %r and showed %r" % (it["id"], 2 * n[0], 2 * n[1], n[0], n[1], got[0], got[2]))
            # 3b. Add where subtract was needed: the letter doubles.
            it = next(x for x in bank["stage2"] if right_answers(x, "stage2")[1] == ("choose", "sub"))
            await page.evaluate("id => SS.ui.startWith('stage2', [id])", it["id"])
            steps = right_answers(it, "stage2")
            await do(page, *steps[0])
            await do(page, "choose", "add")
            i = 0 if it["elim"] == "x" else 1
            dbl = 2 * it["m"][0] * it["e"][0][i]
            got = await page.evaluate("""() => { const f = document.getElementById('feedback'), d = f.querySelector('.doubled');
              return [f.innerText.replace(/\\s+/g, ' '), d ? d.innerText.replace(/\\s+/g, '') : null]; }""")
            if "doubles instead of vanishing" not in got[0] or not got[1] or str(abs(dbl)) not in got[1]:
                fails.append("page, %s: add instead of subtract showed %r (the doubled term %d%s not shown)" % (it["id"], got, dbl, it["elim"]))
            # 3c. A wrong combined equation: the working term by term, subtracting a negative in brackets.
            it = next(x for x in bank["stage2"] if "subtracting a negative" in negative_work(x["e"], x["elim"]))
            await page.evaluate("id => SS.ui.startWith('stage2', [id])", it["id"])
            steps = right_answers(it, "stage2")
            await do(page, *steps[0])
            await do(page, *steps[1])
            await do(page, "type", [str(int(steps[2][1][0]) + 1), steps[2][1][1]])
            got = await page.evaluate("""() => { const w = document.querySelector('#feedback .fb-work');
              return w ? [w.children.length, w.innerText.replace(/\\s+/g, '')] : null; }""")
            if not got or got[0] != 6 or not re.search(r"−\(−", got[1]):
                fails.append("page, %s: a wrong combined equation showed %r, not three term-by-term lines with − (−…)" % (it["id"], got))
            await next_btn(page)
            # 4. A full game of every stage, every step right.
            for st in STAGES:
                await page.evaluate("SS.ui.restart()")
                await page.evaluate("""s => { document.querySelector('.tab[data-level="gcse"]').click();
                  document.querySelector('.stage-btn[data-stage="' + s + '"]').click(); }""", st)
                await page.evaluate("window.__events = []; window.__submits = [];")
                await page.click("#startBtn")
                nexts = 0
                for k in range(ROUNDS[st]):
                    it = await page.evaluate("SS.ui.item()")
                    letter = (it["neat"] if it["neat"] in ("x", "y") else "y") if st == "stage4" else None
                    for kind, val in right_answers(it, st, letter):
                        await do(page, kind, val)
                    nexts += await next_btn(page)
                stt = await page.evaluate("[SS.ui.state(), SS.ui.score(), SS.ui.maxMarks(), !!document.querySelector('#timer, .timer, .hud-timer')]")
                want = ROUNDS[st] * STEPS[st]
                if stt[0] != "done" or stt[1] != want or stt[2] != want or stt[3] or nexts != ROUNDS[st]:
                    fails.append("page, %s full game: state %r, score %r of %r (want %d), timer %s, Next %d times" % (st, stt[0], stt[1], stt[2], want, stt[3], nexts))
                subs = await page.evaluate("window.__submits")
                if subs != [[SLUG, BOARDS[st], want, ROUNDS[st]]]:
                    fails.append("page, %s: leaderboard submissions %r, expected one to %s" % (st, subs, BOARDS[st]))
                ev = await page.evaluate("window.__events")
                bad = [n for n, pr in ev if pr.get("mode") != st or (n != "mode_selected" and pr.get("level") != "gcse")]
                if bad or not any(n == "game_completed" for n, _ in ev):
                    fails.append("page, %s: events without mode %s or level gcse: %r" % (st, st, bad))
            # 5. The A-Level level, every answer right, then one wrong answer waits for Next.
            await page.evaluate("SS.ui.restart()")
            await page.evaluate("document.querySelector('.tab[data-level=\"alevel\"]').click(); window.__events = []; window.__submits = [];")
            await page.click("#startBtn")
            for k in range(20):
                c = (await page.evaluate("SS.ui.mcItem()"))["correct"]
                await page.locator("#mcOptions .opt-btn").filter(has=page.locator("xpath=.")).nth(0).wait_for()
                await page.evaluate("c => [...document.querySelectorAll('#mcOptions .opt-btn')].find(b => b.dataset.val === c).click()", c)
                await page.wait_for_function("SS.ui.state() === 'done' || (SS.ui.mcItem() && document.querySelectorAll('#mcOptions .opt-btn:disabled').length === 0)")
            stt = await page.evaluate("[SS.ui.state(), SS.ui.score()]")
            subs = await page.evaluate("window.__submits")
            if stt != ["done", 2000] or subs != [[SLUG, "alevel", 2000, 20]]:
                fails.append("page, A-Level: state and score %r, submissions %r (want 2000 on 'alevel')" % (stt, subs))
            ev = await page.evaluate("window.__events")
            if any(pr.get("mode") != "choice" or pr.get("level") != "alevel" for n, pr in ev):
                fails.append("page, A-Level: an event without mode 'choice' or level 'alevel': %r" % ev[:3])
            await page.evaluate("SS.ui.startWith('alevel', ['a01'])")
            await page.evaluate("[...document.querySelectorAll('#mcOptions .opt-btn')].find(b => b.dataset.val !== SS.ui.mcItem().correct).click()")
            if not await page.locator("#mcFeedback .maffs-next").count():
                fails.append("page, A-Level: a wrong answer shows no Next control")
            for e in errors:
                fails.append("page error: %s" % e)
            await ctx.close()

            # 6. A full Stage 4 problem on the keypad, on phones: every step and its keypad in the window together.
            it4 = next(x for x in bank["stage4"] if x["neat"] in ("x", "y") and negative_work(x["e"], x["neat"]))
            for (w, h) in PHONES:
                for aa in (False, True):
                    tag = "%dx%d%s" % (w, h, " Aa" if aa else "")
                    ctx, page, errors = await fresh(w, h, touch=True, aa=aa)
                    await page.evaluate("id => SS.ui.startWith('stage4', [id])", it4["id"])
                    for sn, (kind, val) in enumerate(right_answers(it4, "stage4", it4["neat"])):
                        m = await page.evaluate(FIT_JS)
                        if m["top"] < 0 or m["bottom"] > m["fold"]:
                            fails.append("%s %s step %d: the step and its keypad span y=%.0f..%.0f, the window ends at %.0f"
                                         % (tag, it4["id"], sn + 1, m["top"], m["bottom"], m["fold"]))
                        if m["sw"] > m["cw"]:
                            fails.append("%s %s step %d: the page is %dpx wide" % (tag, it4["id"], sn + 1, m["sw"]))
                        if shots and not aa:
                            await page.screenshot(path=os.path.join(shots, "ss-%dx%d-step%d.png" % (w, h, sn + 1)))
                        if kind == "choose":
                            await page.locator('.choice[data-val="%s"]' % val).tap()
                            continue
                        boxes = page.locator("#stepBody input")
                        if await boxes.count() != len(val):
                            fails.append("%s step %d: %d boxes, expected %d" % (tag, sn + 1, await boxes.count(), len(val)))
                            break
                        for bi, v in enumerate(val):
                            await boxes.nth(bi).tap()
                            for ch in v:
                                await page.locator('.maffs-keypad-key[data-act="%s"]%s' % (("minus", "") if ch == "-" else ("in", '[data-val="%s"]' % ch))).tap()
                        got = await page.evaluate("[...document.querySelectorAll('#stepBody input')].map(i => i.value)")
                        if got != val:
                            fails.append("%s step %d: the keypad typed %r, expected %r" % (tag, sn + 1, got, val))
                        if (await page.evaluate(FIT_JS))["focused"]:
                            fails.append("%s step %d: a box took focus (the system keyboard would open)" % (tag, sn + 1))
                        await page.locator("#checkBtn").tap()
                    st4 = await page.evaluate("[SS.ui.state(), SS.ui.score()]")
                    nb = await page.evaluate("(() => { const b = document.querySelector('#feedback .maffs-next'); if (!b) return null; "
                                             "const r = b.getBoundingClientRect(), f = document.getElementById('feedback').getBoundingClientRect(); "
                                             "return [r.bottom, innerHeight - 40, f.top]; })()")
                    if st4 != ["feedback", 5]:
                        fails.append("%s: the Stage 4 problem played on the keypad ended %r, expected ['feedback', 5]" % (tag, st4))
                    if nb is None or nb[0] > nb[1] or nb[2] < 0:
                        fails.append("%s: the answer and Next are not all in the window (Next bottom, fold, feedback top: %r)" % (tag, nb))
                    if shots and not aa:
                        await page.screenshot(path=os.path.join(shots, "ss-%dx%d-end.png" % (w, h)))
                    for e in errors:
                        fails.append("%s page error: %s" % (tag, e))
                    await ctx.close()
            await browser.close()
            return pairs

    server, base = bc.start_stub_server()
    try:
        return asyncio.run(run(base))
    finally:
        server.terminate()


# ---------------------------------------------------------------- Stage 5 (SIM-S5, Jon, 9 Oct 2026)
# Word problems: the student builds the two equations from tiles; a line is right when it is a non-zero multiple
# of a key. The solutions are held here only (the page never has them, so it cannot show them).
S5_SOLUTIONS = {
    "W01": {"a": "8", "c": "6"},
    "W02": {"c": "2.8", "t": "1.7"},
    "W03": {"p": "0.5", "r": "0.3"},
    "W04": {"b": "3.6", "f": "2.7"},
    "W05": {"a": "70", "c": "50"},
    "W06": {"x": "19", "y": "12"},
    "W07": {"x": "36", "y": "12"},
    "W08": {"f": "3.6", "m": "1.5"},
    "W09": {"f": "40", "h": "35"},
    "W10": {"j": "35", "m": "20"},
    "W11": {"c": "20", "s": "10"},
    "W12": {"c": "25", "m": "15"},
    "W13": {"t": "13", "w": "12"},
    "W14": {"s": "35", "c": "25"},
    "W15": {"l": "11", "w": "6"},
    "W16": {"l": "17", "s": "10"},
    "W17": {"s": "1.2", "c": "2.35"},
    "W18": {"f": "11", "n": "7"},
    "W19": {"s": "140", "c": "60"},
    "W20": {"j": "20", "a": "16"},
    "E01": {"p": "300", "q": "170"},
    "E02": {"e": "17", "s": "8"},
    "E03": {"f": "210", "a": "75"},
    "E04": {"s": "10", "p": "3"},
    "E05": {"i": "10", "j": "4"},
    "E06": {"n": "14", "s": "2"},
    "E07": {"s": "12", "a": "5"},
    "E08": {"f": "40", "k": "1.5"},
    "E09": {"a": "44", "b": "20"},
    "E10": {"o": "7", "c": "5"},
    "E11": {"p": "300", "q": "600"},
    "E12": {"d": "110", "c": "80"},
    "E13": {"s": "0.15", "l": "0.4"},
    "E14": {"s": "600", "f": "900"},
    "E15": {"p": "6", "q": "9"},
    "E16": {"f": "50", "h": "40"},
    "E17": {"l": "1600", "s": "1000"},
    "E18": {"p": "7", "e": "3"},
    "E19": {"s": "35", "p": "5"},
    "E20": {"p": "32", "q": "18"},
}
S5_CONTRACTS = [os.path.join(ROOT, "docs", d, "contracts", "2026-10-09-sim-s5.md") for d in ("handover", "history")]
S5_ROUNDS, S5_EACH = 8, 3


def read_words(src):
    return block(src, "/* WORDS BANK START */", "/* WORDS BANK END */")


def s5_tokens(s):
    out = []
    for m in re.finditer(r"(\d[\d,]*(?:\.\d+)?)|([a-z])|([+=])|([-−])", s):
        out.append({"k": "n", "v": m.group(1)} if m.group(1) else {"k": "l", "v": m.group(2)} if m.group(2)
                   else {"k": m.group(3)} if m.group(3) else {"k": "-"})
    return out


def s5_letters(item):
    out = []
    for c in re.findall(r"[a-z]", " ".join(item["keys"])):
        if c not in out:
            out.append(c)
    return out


def s5_vec(tokens, letters):
    """This script's own reading of a line: [A, B, C] for A l1 + B l2 + C = 0, exact; None if not an equation."""
    def side(t):
        acc, i, sign = [Fraction(0)] * 3, 0, 1
        if not t:
            return None
        if t[0]["k"] in "+-":
            sign, i = (-1 if t[0]["k"] == "-" else 1), 1
        while True:
            c, at, has = Fraction(1), 2, False
            if i < len(t) and t[i]["k"] == "n":
                c, has, i = Fraction(t[i]["v"].replace(",", "")), True, i + 1
            if i < len(t) and t[i]["k"] == "l":
                if t[i]["v"] not in letters:
                    return None
                at, has, i = letters.index(t[i]["v"]), True, i + 1
            if not has:
                return None
            acc[at] += sign * c
            if i >= len(t):
                return acc
            if t[i]["k"] not in "+-":
                return None
            sign, i = (-1 if t[i]["k"] == "-" else 1), i + 1
            if i >= len(t):
                return None
    eqs = [i for i, x in enumerate(tokens) if x["k"] == "="]
    if len(eqs) != 1:
        return None
    L, R = side(tokens[:eqs[0]]), side(tokens[eqs[0] + 1:])
    if L is None or R is None:
        return None
    v = [L[j] - R[j] for j in range(3)]
    return v if (v[0] or v[1]) else None


def s5_multiple(v, k):
    return v is not None and (v[0] or v[1]) and all(v[a] * k[b] == v[b] * k[a] for a in range(3) for b in range(a + 1, 3))


def s5_emit(terms):
    """Tokens for a side: terms are (Fraction coefficient, letter or None); zero terms dropped; '0' if empty."""
    out = []
    for c, l in terms:
        if c == 0:
            continue
        if out:
            out.append({"k": "+" if c > 0 else "-"})
        elif c < 0:
            out.append({"k": "-"})
        a = abs(c)
        if l is None or a != 1:
            out.append({"k": "n", "v": s5_num(a)})
        if l is not None:
            out.append({"k": "l", "v": l})
    return out or [{"k": "n", "v": "0"}]


def s5_num(f):
    """A terminating fraction as the decimal a tile shows: 3/10 -> "0.3", 1070 -> "1070"."""
    s = format(Decimal(f.numerator) / Decimal(f.denominator), "f")
    return s.rstrip("0").rstrip(".") if "." in s else s


def s5_forms(item):
    """For each key: the forms the marker must accept and reject (tokens), each with a name."""
    L = s5_letters(item)
    out = []
    for j, key in enumerate(item["keys"]):
        kt = s5_tokens(key)
        e = kt.index({"k": "="})
        A, B, C = s5_vec(kt, L)          # A l1 + B l2 + C = 0
        ints = all(x.denominator == 1 for x in (A, B, C))
        f = Fraction(1, 10) if ints else Fraction(100)
        money = "pounds" in item["let"]
        accept = [("the key", kt), ("sides swapped", kt[e + 1:] + [{"k": "="}] + kt[:e]),
                  ("rearranged", s5_emit([(A, L[0])]) + [{"k": "="}] + s5_emit([(-C, None), (-B, L[1])])),
                  ("scaled by %s" % f, s5_emit([(A * f, L[0]), (B * f, L[1])]) + [{"k": "="}] + s5_emit([(-C * f, None)]))]
        part = Fraction(100 if money else 10)
        partly = (s5_emit([(A, L[0]), (B, L[1])]) + [{"k": "="}] + s5_emit([(-C * part, None)])) if C else \
            (s5_emit([(A * part, L[0]), (B, L[1])]) + [{"k": "="}] + s5_emit([(Fraction(0), None)]))
        reject = [("partly scaled (x%s on %s only)" % (part, "the total" if C else "one term"), partly),
                  ("an arithmetic slip (the total off by 1)", s5_emit([(A, L[0]), (B, L[1])]) + [{"k": "="}] + s5_emit([(-C + 1, None)]))]
        out.append((j, accept, reject))
    return out


def s5_contract_bank():
    for path in S5_CONTRACTS:
        if os.path.exists(path):
            t = open(path, encoding="utf-8").read()
            body = t[t.index("W01 |"):t.rindex("```")]
            rows = {}
            for it in re.split(r" (?=[WE]\d\d \| )", body.strip()):
                f = [x.strip() for x in it.split("|")]
                rows[f[0]] = {"text": f[1], "let": f[2], "keys": [k.strip() for k in f[3].split(";")]}
            return rows
    return None


def check_words(words, report=None):
    """The bank: worded as the contract, each pair solves uniquely to its solution, the Let line names both
    letters, every source quote is in the text, every distractor is a nameable error."""
    fails = []
    ids = [w["id"] for w in words]
    if sorted(ids) != sorted(["W%02d" % i for i in range(1, 21)] + ["E%02d" % i for i in range(1, 21)]):
        fails.append("stage5: the bank is not W01-W20 and E01-E20: %s" % ids)
    contract = s5_contract_bank()
    for w in words:
        wid, L = w["id"], s5_letters(w)
        if contract is not None and wid in contract:
            for field in ("text", "let", "keys"):
                if w[field] != contract[wid][field]:
                    fails.append("stage5 %s: %s is not as the contract words it: %r" % (wid, field, w[field]))
        vecs = [s5_vec(s5_tokens(k), L) for k in w["keys"]]
        if len(L) != 2 or any(v is None for v in vecs):
            fails.append("stage5 %s: the keys are not two equations in two letters: %s" % (wid, w["keys"]))
            continue
        sy = [sp.Symbol(l) for l in L]
        sol = sp.solve([sp.Rational(v[0]) * sy[0] + sp.Rational(v[1]) * sy[1] + sp.Rational(v[2]) for v in vecs], sy, dict=True)
        want = {sp.Symbol(k): sp.Rational(x) for k, x in S5_SOLUTIONS.get(wid, {}).items()}
        det = vecs[0][0] * vecs[1][1] - vecs[0][1] * vecs[1][0]
        if det == 0 or len(sol) != 1 or sol[0] != want:
            fails.append("stage5 %s: the keys %s do not have exactly the one solution %s (got %s)" % (wid, w["keys"], want, sol))
        elif not all(x > 0 for x in want.values()):
            fails.append("stage5 %s: the solution %s is not positive" % (wid, want))
        if not all(re.search(r"\b%s\b" % l, w["let"]) for l in L):
            fails.append("stage5 %s: the Let line does not name both letters %s" % (wid, L))
        for j, s in enumerate(w["src"]):
            if s not in w["text"]:
                fails.append("stage5 %s: key %d's source words %r are not in the problem" % (wid, j + 1, s))
        need = {Fraction(t["v"].replace(",", "")) for k in w["keys"] for t in s5_tokens(k) if t["k"] == "n"}
        text_nums = {Fraction(m.replace(",", "")) for m in re.findall(r"\d[\d,]*(?:\.\d+)?", w["text"])}
        pence = {Fraction(m.replace(",", "")) * 100 for m in re.findall(r"£(\d[\d,]*\.\d\d)", w["text"])} if "pounds" in w["let"] else set()
        for x in w["extra"]:
            v = Fraction(x.replace(",", ""))
            if v in need or v == 1:
                fails.append("stage5 %s: distractor %s is a number the keys use (or 1)" % (wid, x))
            elif v not in text_nums and v not in pence:
                fails.append("stage5 %s: distractor %s is neither a number in the problem nor a pounds amount in pence" % (wid, x))
    if report is not None:
        few = [w["id"] for w in words if len(w["extra"]) < 2]
        report.append("stage5: %d problems; %d with fewer than two distractors (the text has no spare number): %s"
                      % (len(words), len(few), ", ".join(few)))
    return fails


S5_MARK_JS = """(cases) => cases.map(c => {
  const L = SS.formLetters(c.item), keys = c.item.keys.map(k => SS.EqTiles.parse(SS.EqTiles.tokens(k), L).vec);
  const vecs = c.lines.map(t => { const p = SS.EqTiles.parse(t, L); return p.ok ? p.vec : null; });
  if (vecs.some(v => v === null)) return null;
  return SS.EqTiles.markAll(vecs, keys).map(r => r.ok);
})"""
S5_TILES_JS = """(words) => words.map(w => ({ id: w.id, letters: SS.formLetters(w), numbers: SS.formNumbers(w).map(n => n.v) }))"""
S5_TAP_JS = """(arg) => { const [line, key] = arg;
  document.querySelectorAll('#formBuilder .eqt-line')[line].click();
  for (const t of SS.EqTiles.tokens(key)) {
    const v = t.v ? t.v.replace(/,/g, '') : '';
    const b = [...document.querySelectorAll('#formBuilder .eqt-tile')].find(x => x.dataset.k === t.k &&
      (t.k !== 'n' || (SS.EqTiles.num(x.dataset.v)[0] * SS.EqTiles.num(v)[1] === SS.EqTiles.num(v)[0] * SS.EqTiles.num(x.dataset.v)[1])) &&
      (t.k !== 'l' || x.dataset.v === t.v));
    if (!b) return false;
    b.click();
  }
  return true; }"""
S5_HOOKS = """(() => { window.__ev = []; window.__sub = []; let inner;
  Object.defineProperty(window, 'mfg', { configurable: true,
    get() { return function (e, p) { window.__ev.push([e, p]); return inner && inner.apply(this, arguments); }; },
    set(v) { inner = v; } });
  Object.defineProperty(window, 'MaffsLeaderboard', { configurable: true,
    get() { return { submitScore() { window.__sub.push([...arguments]); return Promise.resolve(); } }; }, set(v) {} });
})();"""


def s5_page(browser, base, src, viewport=(390, 844), mobile=True, fresh=False):
    import bank_common as bc
    ctx = browser.new_context(viewport={"width": viewport[0], "height": viewport[1]}, is_mobile=mobile, has_touch=mobile,
                              reduced_motion="reduce")
    if not fresh:
        ctx.add_init_script(bc.NO_LOCK_FRESH_INIT)
    ctx.add_init_script(bc.NO_NEXT_FLOOR_INIT)
    ctx.add_init_script(S5_HOOKS)
    page = ctx.new_page()
    errors = []
    page.on("pageerror", lambda e: errors.append(str(e).splitlines()[0]))
    page.route("**/games/%s/**" % SLUG, lambda r: r.fulfill(status=200, content_type="text/html; charset=utf-8", body=src))
    page.goto("%s/games/%s/?cb=s5" % (base.rstrip("/"), SLUG))
    page.wait_for_function("window.SS && SS.ui && SS.EqTiles")
    return ctx, page, errors


def check_stage5(src, words, only=("marker", "tiles", "play")):
    """Stage 5 in Chromium: the page's own marker on every key's forms, the page's own tiles, a session played."""
    from playwright.sync_api import sync_playwright
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import bank_common as bc
    fails = []
    proc, base = bc.start_stub_server()
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            ctx, page, errors = s5_page(browser, base, src)
            if "marker" in only:
                cases, names = [], []
                for w in words:
                    for j, accept, reject in s5_forms(w):
                        other = s5_tokens(w["keys"][1 - j])
                        for name, toks in accept:
                            v = s5_vec(toks, s5_letters(w))
                            if not s5_multiple(v, s5_vec(s5_tokens(w["keys"][j]), s5_letters(w))):
                                fails.append("stage5 %s: this script's own %s form of key %d is not a multiple of it" % (w["id"], name, j + 1))
                            cases.append({"item": w, "lines": [toks, other] if j == 0 else [other, toks]})
                            names.append((w["id"], j, name, True))
                        for name, toks in reject:
                            cases.append({"item": w, "lines": [toks, other] if j == 0 else [other, toks]})
                            names.append((w["id"], j, name, False))
                    k0 = s5_tokens(w["keys"][0])
                    cases.append({"item": w, "lines": [k0, k0]})
                    names.append((w["id"], 0, "the same key twice", None))
                got = page.evaluate(S5_MARK_JS, cases)
                for (wid, j, name, want), g in zip(names, got):
                    if g is None:
                        fails.append("stage5 %s: the page cannot read the %s form of key %d" % (wid, name, j + 1))
                    elif want is None and g != [True, False]:
                        fails.append("stage5 %s: the same key twice marked %s (right, then wrong)" % (wid, g))
                    elif want is not None and g[j] is not want:
                        fails.append("stage5 %s: the %s form of key %d marked %s, expected %s" % (wid, name, j + 1, "right" if g[j] else "wrong", "right" if want else "wrong"))
            if "tiles" in only:
                for t, w in zip(page.evaluate(S5_TILES_JS, words), words):
                    have = {Fraction(x) for x in t["numbers"]}
                    for k in w["keys"]:
                        for tok in s5_tokens(k):
                            if tok["k"] == "n" and Fraction(tok["v"].replace(",", "")) not in have:
                                fails.append("stage5 %s: no tile for %s, so the key %r cannot be built" % (w["id"], tok["v"], k))
                            if tok["k"] == "l" and tok["v"] not in t["letters"]:
                                fails.append("stage5 %s: no tile for the letter %s" % (w["id"], tok["v"]))
            ctx.close()
            if "play" in only:
                fails += s5_play(browser, base, src, words)
            if errors:
                fails.append("stage5: page errors: %s" % "; ".join(errors[:3]))
            browser.close()
    finally:
        proc.terminate()
        proc.wait()
    return fails


def s5_play(browser, base, src, words):
    fails = []
    byid = {w["id"]: w for w in words}
    # sessions: eight problems, none repeated, at least three W and three E
    ctx, page, errors = s5_page(browser, base, src, (1280, 900), mobile=False)
    for _ in range(60):
        ids = page.evaluate("""() => { SS.ui.restart(); document.querySelector('.stage-btn[data-stage="stage5"]').click();
          document.getElementById('startBtn').click(); return SS.ui.formIds(); }""")
        nw, ne = sum(i[0] == "W" for i in ids), sum(i[0] == "E" for i in ids)
        if len(ids) != S5_ROUNDS or len(set(ids)) != S5_ROUNDS or nw < S5_EACH or ne < S5_EACH:
            fails.append("stage5: a session drew %s (eight, none repeated, three W and three E at least)" % ids)
            break
    ctx.close()
    # a whole session on each screen, built by tapping the tiles: right, swapped order, then one line wrong
    for vp, mobile in (((390, 844), True), ((1280, 900), False)):
        ctx, page, errors = s5_page(browser, base, src, vp, mobile)
        page.evaluate("() => { document.querySelector('.stage-btn[data-stage=\"stage5\"]').click(); document.getElementById('startBtn').click(); }")
        widths, marks_want, n = [], 0, 0
        while page.evaluate("document.getElementById('form').classList.contains('active')") and n < 12:
            it = byid[page.evaluate("SS.ui.formItem().id")]
            wrong = n % 3 == 2
            lines = [it["keys"][1], it["keys"][0]] if n % 3 == 1 else [it["keys"][0], it["keys"][0] if wrong else it["keys"][1]]
            for li, key in enumerate(lines):
                if not page.evaluate(S5_TAP_JS, [li, key]):
                    fails.append("stage5 %s at %dx%d: the tiles could not build %r" % (it["id"], vp[0], vp[1], key))
            page.click("#formCheck")
            marks_want += 1 if wrong else 2
            widths.append(page.evaluate("document.documentElement.scrollWidth"))
            got = int(page.evaluate("document.getElementById('formMarks').textContent"))
            if got != marks_want:
                fails.append("stage5 %s at %dx%d: marks %d after it, expected %d" % (it["id"], vp[0], vp[1], got, marks_want))
            if wrong:
                fb = page.evaluate("document.getElementById('formFeedback').innerText")
                if it["src"][1] not in fb or it["keys"][1].split("=")[0].strip()[:2] not in fb.replace("−", "-"):
                    fails.append("stage5 %s: the feedback does not show key 2 and its words: %r" % (it["id"], fb[:120]))
                page.wait_for_selector("#formFeedback .maffs-next:not([disabled])")
                page.click("#formFeedback .maffs-next")
            else:
                page.wait_for_function("(id) => !document.getElementById('form').classList.contains('active') || SS.ui.formItem().id !== id",
                                       arg=it["id"], timeout=6000)
            n += 1
        res = page.evaluate("""() => ({ results: document.getElementById('results').classList.contains('active'),
          qa: __ev.filter(e => e[0] === 'question_answered').length, sub: __sub.map(s => s[1] + ':' + s[2]),
          modes: [...new Set(__ev.map(e => (e[1] || {}).mode).filter(Boolean))] })""")
        if not res["results"] or n != S5_ROUNDS or res["qa"] != S5_ROUNDS or res["sub"] != ["foundation-s5:%d" % marks_want] \
                or res["modes"] != ["stage5"] or max(widths) > vp[0]:
            fails.append("stage5 at %dx%d: %d problems, %s; page width up to %d px" % (vp[0], vp[1], n, res, max(widths)))
        if errors:
            fails.append("stage5 at %dx%d: page errors %s" % (vp[0], vp[1], errors[:2]))
        ctx.close()
    # MaffsLock with its real window: a double tap on Check marks once; tiles do nothing after it
    ctx, page, errors = s5_page(browser, base, src, fresh=True)
    page.evaluate("() => { document.querySelector('.stage-btn[data-stage=\"stage5\"]').click(); document.getElementById('startBtn').click(); }")
    page.wait_for_function("() => !MaffsLock.isFresh()")
    it = byid[page.evaluate("SS.ui.formItem().id")]
    page.evaluate(S5_TAP_JS, [0, it["keys"][0]])
    page.evaluate(S5_TAP_JS, [1, it["keys"][1]])
    page.evaluate("() => { const b = document.getElementById('formCheck'); b.click(); b.click(); b.click(); }")
    before = page.evaluate("JSON.stringify(SS.ui.formRead())")
    page.evaluate("() => document.querySelector('#formBuilder .eqt-tile').click()")
    st = page.evaluate("""(b) => ({ marks: document.getElementById('formMarks').textContent,
      qa: __ev.filter(e => e[0] === 'question_answered').length, same: JSON.stringify(SS.ui.formRead()) === b })""", before)
    if st != {"marks": "2", "qa": 1, "same": True}:
        fails.append("stage5: a triple click on Check, then a tile: %s (2 marks, one event, the lines unchanged)" % st)
    ctx.close()
    return fails


def s5_selftest(src, words):
    """Each planted fault must fail: a problem with two solutions, a marker that compares strings, tiles that
    cannot build a key."""
    out = []
    bad = copy.deepcopy(words)
    w = next(x for x in bad if x["id"] == "W06")
    w["keys"][1] = "2x + 2y = 62"
    hits = [f for f in check_words(bad) if "W06" in f and "solution" in f]
    out.append(("a problem with two solutions (W06's second key 2x + 2y = 62)", hits))
    marker = "if (mark(v, keys[k])) j = k;"
    planted = src.replace(marker, "if (JSON.stringify(v) === JSON.stringify(keys[k])) j = k;")
    hits = [f for f in check_stage5(planted, words, only=("marker",)) if "marked" in f] if planted != src else ["(no marker to plant over)"]
    out.append(("a marker that compares the equations as written", hits))
    tiles = "it.keys.forEach(function (k) { EqTiles.tokens(k).forEach(function (t) { if (t.k === 'n') put(t.v); }); });"
    planted = src.replace(tiles, "EqTiles.tokens(it.keys[0]).forEach(function (t) { if (t.k === 'n') put(t.v); });")
    hits = [f for f in check_stage5(planted, words, only=("tiles",)) if "no tile" in f] if planted != src else ["(no tile rule to plant over)"]
    out.append(("tiles that cannot build key 2", hits))
    fails = []
    for name, hits in out:
        print("  self-test stage5 %-62s %s" % (name, ("caught: " + hits[0][:80]) if hits else "*** MISSED ***"))
        if not hits or hits[0].startswith("(no "):
            fails.append("stage5 self-test: %s was not caught" % name)
    return fails


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--static", action="store_true", help="the banks only, no browser")
    ap.add_argument("--katex-dir", help="serve KaTeX from this copy of its dist/ folder (a sandbox where the CDN is blocked)")
    ap.add_argument("--shots", help="save the phone screenshots of the Stage 4 problem here")
    args = ap.parse_args()
    bank, alevel = read_banks()
    fails = selftest(bank, alevel)
    report = []
    fails += check_foundation(bank, report)
    fails += check_alevel(alevel)
    gen = load_gen()
    if gen.render(gen.build()) != open(PAGE, encoding="utf-8").read().split("/* GENERATED BANK START */\n", 1)[1].split("\n/* GENERATED BANK END */", 1)[0]:
        fails.append("the page's bank is not what scripts/gen-simultaneous.py generates (run it with --write)")
    src = open(PAGE, encoding="utf-8").read()
    words = read_words(src)
    fails += check_words(words, report)
    pairs = 0
    if not args.static:
        fails += s5_selftest(src, words)
        if not fails:
            fails += check_stage5(src, words)
    if not args.static and not fails:
        if args.shots:
            os.makedirs(args.shots, exist_ok=True)
        pairs = play(fails, bank, alevel, args.katex_dir, args.shots)
    for line in report:
        print(line)
    if fails:
        for f in fails:
            print("FAIL " + f)
        print("\nFAILED: %d problem(s)" % len(fails))
        return 1
    print("\nPASS: %s; stage5 %d word problems; %d A-Level questions; self-test 4/4 planted faults caught%s%s"
          % (", ".join("%s %d" % (s, len(bank[s])) for s in STAGES), len(words), len(alevel),
             "" if args.static else "; stage5 self-test 3/3 caught",
             "" if args.static else "; %d Stage 1 multiplier pairs marked in Chromium; phones %s typed on the keypad"
             % (pairs, ", ".join("%dx%d" % p for p in PHONES))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
